pipeline {
  agent any
  environment {
    RELEASE = '20.04'
  }
  stages {
    stage('Build') {
      environment {
         LOG_LEVEL='INFO' 
      }
      steps {
        echo "Building release ${RELEASE} at log level ${LOG_LEVEL}..."
        sh 'chmod +x jenkin/3.2/build.sh'
        withCredentials([string(credentialsId: 'an-api-key', variable: 'API_KEY')]) {
           sh '''
              ./jenkins/3.2/build.sh
           '''
        }
      }
    }
    stage('Test') {
      steps {
        echo "Testing release ${RELEASE}"
        writeFile file: 'test-results.txt', text: 'passed'
      }
    }
  }
  post {
    success {
      archiveArtifacts 'test-results.txt' 
      slackSedn channel: '#builds',
        message: "Release ${env.RELEASE}, success: ${currentBuild.fullDisplayName}."
    }
    failure {
      archiveArtifacts 'test-results.txt' 
      slackSedn channel: '#builds',
        message: "Release ${env.RELEASE}, success: ${currentBuild.fullDisplayName}."
    }
  }
}
