library identifier: './jenkins@main', 
        retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/WilsonLum/git-Covid.git'])

pipeline {
    agent any
    stages {
        stage('Audit tools') {                        
            steps {
                auditTools2 message: 'This is demo 2'
            }
        }
    }
}
