pipeline {
  agent any
  environment {
    RELEASE = '20.04'
  }
  stages {
    stage('Build') {
      environment {
         LOG_LEVEL='INFO' 
      }
      steps {
        echo "Testing release ${RELEASE} at log level ${LOG_LEVEL}"
        writeFile file: 'test-results.txt', text: 'passed'
      }
    }
    stage('Test') {
      steps {
        echo "Testing. I can see release ${RELEASE}"
      }
    }
  }
  post {
    success {
      arhiveArtifacts 'test-results.txt' 
    }
  }
}
